services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: house-factory-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/house-factory.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: house-factory-postgres
    environment:
      POSTGRES_DB: iiot_history
      POSTGRES_USER: iiot_user
      POSTGRES_PASSWORD: iiot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iiot_user -d iiot_history"]
      interval: 5s
      timeout: 5s
      retries: 10

  simulator:
    build: .
    container_name: house-factory-simulator
    depends_on:
      - mosquitto
    command: ["python", "src/house_factory_simulator.py"]
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      BASE_TOPIC: plain-uns/v1/house-factory/line-01
      PUBLISH_INTERVAL_SECONDS: 1
    restart: unless-stopped

  opcua-server:
    build: .
    container_name: house-factory-opcua
    depends_on:
      - mosquitto
      - simulator
    command: ["python", "src/house_factory_opcua_server.py"]
    ports:
      - "4840:4840"
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      SOURCE_BASE_TOPIC: plain-uns/v1/house-factory/line-01
      OPCUA_HOST: 0.0.0.0
      OPCUA_PORT: 4840
      OPCUA_ENDPOINT: opc.tcp://0.0.0.0:4840/house-factory/server/
      OPCUA_NAMESPACE_URI: urn:house-factory:line-01
      OPCUA_SERVER_NAME: House Factory OPC UA Server
      OPCUA_UPDATE_INTERVAL_SECONDS: 0.2
    restart: unless-stopped

  sparkplug:
    build: .
    container_name: house-factory-sparkplug
    depends_on:
      - mosquitto
      - simulator
    command: ["python", "src/house_factory_sparkplug.py"]
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      SOURCE_BASE_TOPIC: plain-uns/v1/house-factory/line-01
      SPARKPLUG_NAMESPACE: spBv1.0
      SPARKPLUG_GROUP_ID: house-factory
      SPARKPLUG_EDGE_NODE_ID: line-01
      SPARKPLUG_CLIENT_ID: manual-sparkplug-bridge-line-01
      SPARKPLUG_PUBLISH_INTERVAL_SECONDS: 1
      SPARKPLUG_INITIAL_WAIT_SECONDS: 5
    restart: unless-stopped

  postgres-logger:
    build: .
    container_name: house-factory-postgres-logger
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started
      simulator:
        condition: service_started
    command: ["python", "src/house_factory_postgres_logger.py"]
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      SUBSCRIBE_TOPIC: plain-uns/v1/house-factory/line-01/#
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DATABASE: iiot_history
      PG_USER: iiot_user
      PG_PASSWORD: iiot_password
      RETENTION_HOURS: 24
      CLEANUP_INTERVAL_SECONDS: 1800
      BATCH_SIZE: 100
      FLUSH_INTERVAL_SECONDS: 2
      PRINT_EVERY_BATCH: "true"
    restart: unless-stopped

  modbus-bridge:
    build: .
    container_name: house-factory-modbus-bridge
    depends_on:
      - mosquitto
      - simulator
    command: ["python", "src/house_factory_modbus_bridge.py"]
    ports:
      - "5021:5021"
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      SOURCE_BASE_TOPIC: plain-uns/v1/house-factory/line-01
      MODBUS_HOST: 0.0.0.0
      MODBUS_PORT: 5021
    restart: unless-stopped

  sqlite-logger:
    build: .
    container_name: house-factory-sqlite-logger
    depends_on:
      - mosquitto
      - simulator
    command: ["python", "src/house_factory_sql_logger.py"]
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      SUBSCRIBE_TOPIC: plain-uns/v1/house-factory/line-01/#
      SQLITE_DB_FILE: /data/iiot_history.db
      RETENTION_HOURS: 24
      CLEANUP_INTERVAL_SECONDS: 60
    volumes:
      - sqlite_data:/data
    restart: unless-stopped

  aws-iot-publisher:
    build: .
    container_name: house-factory-aws-iot-publisher
    depends_on:
      - mosquitto
      - simulator
    command: ["python", "src/house_factory_aws_iot_publisher.py"]
    environment:
      LOCAL_MQTT_HOST: mosquitto
      LOCAL_MQTT_PORT: 1883
      LOCAL_SUBSCRIBE_TOPIC: plain-uns/v1/house-factory/line-01/#
      LOCAL_BASE_TOPIC: plain-uns/v1/house-factory/line-01
      AWS_IOT_ENDPOINT: a39fq8pk1n1f0l-ats.iot.eu-north-1.amazonaws.com
      AWS_CLIENT_ID: basicPubSub
      AWS_CERT_FILE: aws/raspberry-iiot-demo.cert.pem
      AWS_KEY_FILE: aws/raspberry-iiot-demo.private.key
      AWS_ROOT_CA_FILE: aws/root-CA.crt
      AWS_TOPIC_PREFIX: iiot/house-factory/line-01
      CLOUD_PUBLISH_INTERVAL_SECONDS: 5
    volumes:
      - ./aws:/app/aws:ro
    restart: unless-stopped

  api:
    build: .
    container_name: house-factory-api
    depends_on:
      - sqlite-logger
    command: ["python", "src/house_factory_api.py"]
    ports:
      - "8000:8000"
    environment:
      API_TITLE: House Factory IIoT API
      API_HOST: 0.0.0.0
      API_PORT: 8000
      SQLITE_DB_FILE: /data/iiot_history.db
    volumes:
      - sqlite_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  sqlite_data: